# Generated by Django 5.2.5 on 2025-08-14 17:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2025, 8, 14, 17, 29, 14, 421730, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='gender',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='Masculino', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.BigIntegerField(default=4120000000, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='region',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Anzoátegui', 'Anzoátegui'), ('Apure', 'Apure'), ('Aragua', 'Aragua'), ('Barinas', 'Barinas'), ('Bolívar', 'Bolívar'), ('Carabobo', 'Carabobo'), ('Cojedes', 'Cojedes'), ('Delta Amacuro', 'Delta Amacuro'), ('Distrito Capital', 'Distrito Capital'), ('Falcón', 'Falcón'), ('Guárico', 'Guárico'), ('Lara', 'Lara'), ('Mérida', 'Mérida'), ('Miranda', 'Miranda'), ('Monagas', 'Monagas'), ('Nueva Esparta', 'Nueva Esparta'), ('Portuguesa', 'Portuguesa'), ('Sucre', 'Sucre'), ('Táchira', 'Táchira'), ('Trujillo', 'Trujillo'), ('La Guaira', 'La Guaira'), ('Yaracuy', 'Yaracuy'), ('Zulia', 'Zulia')], default='Zulia', max_length=20),
            preserve_default=False,
        ),
    ]
