# Generated by Django 5.2.5 on 2025-08-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
