# Generated by Django 5.2.5 on 2025-10-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_usuario_avatar_path_usuario_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(default='register', max_length=50),
        ),
    ]
