# Generated by Django 5.2.5 on 2025-10-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuario_gender_alter_usuario_region'),
        ('api', '0009_alter_emailverification_email'),
    ]

    operations = [
    ]
