# Generated by Django 5.2.5 on 2025-10-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20251015_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
