# Generated by Django 5.2.5 on 2025-08-17 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre legal de la empresa (único)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('rif', models.CharField(help_text='RIF de la empresa (único)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]-\\d{8}-\\d$', message='Formato de RIF inválido. Ejemplo válido: J-12345678-9')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, help_text='Ubicación o ciudad principal de la empresa', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{7,15}$', message='El teléfono debe tener entre 7 y 15 dígitos.')])),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Debe ser un correo electrónico válido.')])),
                ('redes_sociales', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='Debe ser una URL válida.')])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('seguidores', models.ManyToManyField(blank=True, help_text='Usuarios que siguen esta empresa', related_name='empresas_que_sigue', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(help_text='Usuario administrador de esta empresa', on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('usuario',), name='unique_usuario_empresa')],
            },
        ),
    ]
