# Generated by Django 5.2.5 on 2025-08-21 04:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre legal de la empresa (único)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('rif', models.CharField(help_text='RIF de la empresa (único)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]-\\d{8}-\\d$', message='Formato de RIF inválido. Ejemplo válido: J-12345678-9')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, help_text='Ubicación o ciudad principal de la empresa', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{7,15}$', message='El teléfono debe tener entre 7 y 15 dígitos.')])),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Debe ser un correo electrónico válido.')])),
                ('redes_sociales', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(message='Debe ser una URL válida.')])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('seguidores', models.ManyToManyField(blank=True, help_text='Usuarios que siguen esta empresa', related_name='empresas_que_sigue', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(help_text='Usuario administrador de esta empresa', on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del evento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('categoria', models.JSONField(default=list, help_text='Lista de categorías seleccionadas')),
                ('codigo_vestimenta', models.CharField(choices=[('Formal', 'Formal'), ('Semi-formal', 'Semi-formal'), ('Casual', 'Casual'), ('Deportivo', 'Deportivo'), ('Elegante casual', 'Elegante casual')], help_text='Código de vestimenta (selección)', max_length=50)),
                ('edad_minima', models.PositiveSmallIntegerField(choices=[('Todas las edades', 'Todas las edades'), ('Mayores de 13 años', 'Mayores de 13 años'), ('Mayores de 16 años', 'Mayores de 16 años'), ('Mayores de 18 años', 'Mayores de 18 años'), ('Mayores de 21 años', 'Mayores de 21 años'), ('Mayores de 25 años', 'Mayores de 25 años'), ('Familiar (Todas las edades)', 'Familiar (Todas las edades)')], help_text='Edad mínima para asistir')),
                ('ubicacion', models.CharField(blank=True, help_text='Lugar o dirección del evento', max_length=255, null=True)),
                ('capacidad', models.PositiveIntegerField(default=0, help_text='Cupo máximo de asistentes (0 = ilimitado)')),
                ('precio', models.DecimalField(decimal_places=2, default=0, help_text='Precio de entrada', max_digits=10)),
                ('moneda', models.CharField(default='USD', help_text='Código ISO de moneda (ej. USD, EUR)', max_length=3)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen promocional del evento', null=True, upload_to='eventos_imagenes/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='Empresa dueña de este evento', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.UniqueConstraint(fields=('usuario',), name='unique_usuario_empresa'),
        ),
    ]
