# Generated by Django 5.2.5 on 2025-08-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento2',
            name='descripcion_vestimenta',
            field=models.TextField(blank=True, help_text='Descripción del código de vestimenta', null=True),
        ),
    ]
