# Generated by Django 5.2.5 on 2025-09-03 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento2',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de inicio del evento'),
        ),
    ]
