# Generated by Django 5.2.5 on 2025-09-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_evento2_fecha_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento2',
            old_name='fecha_inicio',
            new_name='fecha_evento',
        ),
    ]
