# Generated by Django 5.2.5 on 2025-09-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_rename_fecha_inicio_evento2_fecha_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='empresa.empresa')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='empresa.evento2')),
            ],
        ),
    ]
