# Generated by Django 5.2.5 on 2025-08-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_evento2_edad_minima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento2',
            name='edad_minima',
            field=models.PositiveSmallIntegerField(choices=[('Todas las edades', 'Todas las edades'), ('13', 'Mayores de 13 años'), ('Mayores de 16 años', 'Mayores de 16 años'), ('Mayores de 18 años', 'Mayores de 18 años'), ('Mayores de 21 años', 'Mayores de 21 años'), ('Mayores de 25 años', 'Mayores de 25 años'), ('Familiar (Todas las edades)', 'Familiar (Todas las edades)')], help_text='Edad mínima para asistir'),
        ),
    ]
