# Generated by Django 5.2.5 on 2025-09-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_empresaevento'),
        ('empresa', '0004_rating'),
    ]

    operations = [
    ]
