# Generated by Django 5.2.5 on 2025-08-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_evento2_edad_minima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento2',
            name='edad_minima',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Todas las edades'), (13, 'Mayores de 13 años'), (16, 'Mayores de 16 años'), (18, 'Mayores de 18 años'), (21, 'Mayores de 21 años'), (25, 'Mayores de 25 años')], help_text='Edad mínima para asistir'),
        ),
    ]
