# Generated by Django 5.2.5 on 2025-08-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_evento2_edad_minima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento2',
            options={'ordering': ['-id'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
