# Generated by Django 5.2.5 on 2025-09-11 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_evento2_latitude_evento2_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento2',
            name='imagen',
        ),
        migrations.CreateModel(
            name='EventoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='empresa.evento2')),
            ],
        ),
    ]
