# Generated by Django 5.2.5 on 2025-08-26 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_evento2_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='empresa',
                help_text='Usuario administrador de esta empresa',
                to='api.Usuario'
            ),
        ),
    ]
