# Generated by Django 5.2.5 on 2025-09-11 19:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_remove_evento2_imagen_eventoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento2',
            name='empresa_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
