# Generated by Django 5.2.5 on 2025-09-11 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_evento2_empresa_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento2',
            name='empresa_uid',
        ),
    ]
