# Generated by Django 5.2.5 on 2025-08-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20250826_1802'),
        ('empresa', '0008_set_cascade_evento2'),
    ]

    operations = [
    ]
