# Generated by Django 5.2.5 on 2025-09-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_usuarioevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento2',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Lugar o dirección del evento', max_length=300, null=True),
        ),
    ]
