# Generated by Django 5.2.5 on 2025-09-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0011_alter_evento2_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoimagen',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
