# Generated by Django 5.2.5 on 2025-09-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0012_eventoimagen_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
