# Generated by Django 5.2.5 on 2025-09-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_empresa_avatar_path_empresa_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto_perfil',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
