# Generated by Django 5.2.5 on 2025-09-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0014_empresa_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='foto_perfil',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
