# Generated by Django 5.2.5 on 2025-09-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0015_remove_empresa_foto_perfil_alter_empresa_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='redes_sociales',
            field=models.JSONField(blank=True, default=dict, help_text="Diccionario de redes sociales: {'instagram': '...', 'facebook': '...'}", null=True),
        ),
    ]
