# Generated by Django 5.2.5 on 2025-09-22 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0016_alter_empresa_redes_sociales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='redes_sociales',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='seguidores',
        ),
        migrations.CreateModel(
            name='EmpresaRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('x', 'X (Twitter)'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField(max_length=512)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='empresa.empresa')),
                ('seguidores', models.ManyToManyField(blank=True, help_text='Usuarios que siguen esta empresa', related_name='empresas_que_sigue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
