# Generated by Django 5.2.5 on 2025-09-23 01:36

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_alter_empresa_options_remove_empresa_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='empresaredsocial',
            options={'verbose_name': 'Red social de empresa', 'verbose_name_plural': 'Redes sociales de empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='empresaredsocial',
            unique_together={('empresa', 'tipo')},
        ),
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='seguidores',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que siguen esta empresa', related_name='empresas_que_sigue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='empresaredsocial',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='empresaredsocial',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='empresaredsocial',
            name='seguidores',
        ),
    ]
