# Generated by Django 5.2.5 on 2025-09-27 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0018_alter_empresa_options_alter_empresaredsocial_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='company_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_verificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['status'], name='empresa_emp_status_cc141b_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['rif'], name='empresa_emp_rif_fb8489_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['email'], name='empresa_emp_email_c7976d_idx'),
        ),
    ]
