# Generated by Django 5.2.5 on 2025-09-28 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0019_empresa_company_verified_empresa_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Validador asignado para revisar esta empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignada'), ('in_review', 'En revisión')], default='pending', help_text='Estado del proceso de revisión (independiente de approved/rejected)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['assigned_to', 'status'], name='empresa_emp_assigne_bdb898_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['review_status'], name='empresa_emp_review__641876_idx'),
        ),
    ]
