# Generated by Django 5.2.5 on 2025-10-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0020_empresa_assigned_at_empresa_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento2',
            name='promote',
            field=models.BooleanField(default=False, help_text='Si el evento es promovido o destacado'),
        ),
        migrations.AddField(
            model_name='evento2',
            name='want_promote',
            field=models.BooleanField(default=False, help_text='Si la empresa quiere promover este evento'),
        ),
    ]
