# Generated by Django 5.2.5 on 2025-10-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0021_evento2_promote_evento2_want_promote'),
        ('empresa', '0021_notificacionusuario'),
    ]

    operations = [
    ]
