# Generated by Django 5.2.5 on 2025-10-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0022_merge_20251011_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='telefono',
            new_name='phone',
        ),
    ]
