# Generated by Django 5.2.5 on 2025-10-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0023_rename_telefono_empresa_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificacionUsuario',
        ),
    ]
