# Generated by Django 5.2.5 on 2025-10-18 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0024_delete_notificacionusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(db_index=True, help_text='Nombre legal de la empresa (único)', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
