# Generated by Django 5.2.5 on 2025-10-26 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0026_companyeventview_companyprofileview'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaMetricNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('perfil', 'Perfil'), ('evento', 'Evento')], max_length=20)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(max_length=20)),
                ('enviado', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'tipo', 'periodo'], name='empresa_emp_empresa_b4a8d8_idx')],
                'unique_together': {('empresa', 'tipo', 'referencia_id', 'periodo')},
            },
        ),
    ]
