# Generated by Django 5.2.5 on 2025-10-26 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0027_empresametricnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='empresa.empresa')),
            ],
            options={
                'indexes': [models.Index(fields=['empresa', 'tipo', 'timestamp'], name='empresa_not_empresa_d296de_idx')],
            },
        ),
    ]
